model_hparams:
  act_fn_name: relu
  bn_size: 2
  growth_rate: 16
  num_classes: 10
  num_layers:
  - 6
  - 6
  - 6
  - 6
model_name: DenseNet
optimizer_hparams:
  lr: 0.001
  weight_decay: 0.0001
optimizer_name: Adam
